#!/usr/bin/env python3
"""
Temple of Sun — give every blend its own page.

Peter has written roughly 10,700 words describing the 23 blends. All of it
lives inside the `DATA` objects in rainbow-collection.html and 5-elements.html,
and only appears after a visitor clicks a tile. Search engines and AI
assistants never click, so until now that writing was invisible to them — and
no blend had an address anyone could link to or cite.

This reads those same `DATA` objects and writes one page per blend:

    blend-focus.html, blend-moonlight.html, ...

Nothing is rewritten. The words are Peter's, moved somewhere readable.

GENERATED FILES — do not edit blend-*.html by hand. Edit the `DATA` entry in
the collection page, then rerun. `tools/prepare-for-upload.py` does this for
you on every run.
"""

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://templeofsun.com"

SOURCES = [
    {
        "file": "rainbow-collection.html",
        "collection": "The Rainbow Collection",
        "collection_url": "rainbow-collection.html",
    },
    {
        "file": "5-elements.html",
        "collection": "The 5 Elements",
        "collection_url": "5-elements.html",
    },
]

PAGE = """<!DOCTYPE html>
<html lang="en" data-root="../">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="icon" type="image/svg+xml" href="../assets/favicon.svg">
<link rel="stylesheet" href="../css/site.css">
<script src="../js/img-fallback.js"></script>
<!-- generated by tools/generate-product-pages.py — do not edit by hand -->
<link rel="canonical" href="{url}">
<meta name="robots" content="max-snippet:-1, max-image-preview:large">
<meta property="og:type" content="product">
<meta property="og:site_name" content="Temple of Sun">
<meta property="og:title" content="{og_title}">
<meta property="og:description" content="{description}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{image_abs}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{og_title}">
<meta name="twitter:description" content="{description}">
<meta name="twitter:image" content="{image_abs}">
<meta name="theme-color" content="#FAF6EF">
<link rel="apple-touch-icon" href="../assets/apple-touch-icon.png">
<link rel="preload" as="font" type="font/woff2" href="../assets/fonts/cormorant-garamond-latin-600-normal.woff2" crossorigin>
<link rel="preload" as="font" type="font/woff2" href="../assets/fonts/inter-latin-400-normal.woff2" crossorigin>
<link rel="preload" as="image" href="../{image}">
<script type="application/ld+json">{schema}</script>
</head>
<body>

<header data-site-header class="site-header"></header>
<div data-site-mobile class="mobile-menu"></div>

<main class="bp">

  <section class="bp-hero">
    <div class="bp-hero-in">

      <nav class="bp-crumbs" aria-label="Breadcrumb">
        <a href="../index.html">Home</a> <span aria-hidden="true">·</span>
        <a href="../collections.html">Collections</a> <span aria-hidden="true">·</span>
        <a href="../{collection_url}">{collection}</a>
      </nav>

      <div class="bp-hero-grid">
        <figure class="bp-shot reveal">
          <span class="frame"><img src="../{image}"
            alt="{name}, a hand-blended aromatherapy oil by Temple of Sun"
            width="640" height="640" fetchpriority="high" decoding="async" data-onerr="hide"></span>
        </figure>

        <div class="bp-lede">
          <h1>{name}</h1>
          <p class="bp-for">For {forline}.</p>
          <p class="bp-price"><strong>{price}</strong> <span>· {size}</span></p>
          <div class="bp-cta">
            <a class="btn btn-solid" href="../contact.html?topic=order">Enquire about {name}</a>
            <a class="btn" href="https://wa.me/36702879225" target="_blank" rel="noopener">Ask Peter</a>
          </div>
          <dl class="bp-facts">
            <div><dt>Collection</dt><dd><a href="../{collection_url}">{collection}</a></dd></div>
            <div><dt>Size</dt><dd>{size}</dd></div>
            <div><dt>Blended by</dt><dd>Péter Frák, IFA member</dd></div>
          </dl>
        </div>
      </div>

    </div>
  </section>

  <div class="bp-columns">

    <article class="bp-body">
{body}
    </article>

    <aside class="bp-rail" aria-label="Order {name}">
      <div class="bp-rail-in">
        <p class="bp-rail-price"><strong>{price}</strong> <span>{size}</span></p>
        <a class="btn btn-solid bp-rail-btn" href="../contact.html?topic=order">Enquire about {name}</a>
        <a class="btn bp-rail-btn" href="https://wa.me/36702879225" target="_blank" rel="noopener">Ask Peter</a>
        <p class="bp-rail-note">Blended by Péter Frák from 100% pure, laboratory-tested
        essential oils, in a meditative state, with blessings and intention.</p>
        <p class="bp-rail-quiz">Not sure this is yours?
        <a href="../find-your-blend.html">Find your blend</a></p>
      </div>
    </aside>

  </div>

  <section class="bp-more">
    <div class="bp-more-in">
      <h2>More from {collection}</h2>
      <ul class="bp-more-grid">
{more}
      </ul>
      <p class="bp-more-all"><a href="../{collection_url}">See all of {collection}</a></p>
    </div>
  </section>

</main>

<footer data-site-footer class="site-footer"></footer>

<script src="../js/site.js"></script>
</body>
</html>
"""


def esc(text) -> str:
    return html.escape(str(text), quote=True)


def load(source: dict) -> dict:
    path = ROOT / source["file"]
    text = path.read_text(encoding="utf-8")
    match = re.search(r"var DATA = (\{.*?\});\s*\n", text, re.S)
    if not match:
        sys.exit(f"ERROR: no DATA object found in {source['file']}")
    return json.loads(match.group(1))


def plain(fragment: str) -> str:
    """First readable sentence-ish chunk of the description, for meta tags."""
    text = re.sub(r"<[^>]+>", " ", fragment)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def build_schema(slug: str, blend: dict, source: dict, url: str, image_abs: str) -> str:
    price = blend["price"].replace("€", "").strip()
    description = f"For {blend['forline']}. Hand-blended by Péter Frák of Temple of Sun."

    product = {
        "@type": "Product",
        "@id": f"{url}#product",
        "name": f"{blend['name']} essential oil blend",
        "sku": slug,
        "url": url,
        "description": description,
        "image": image_abs,
        "brand": {"@type": "Brand", "name": "Temple of Sun"},
        "manufacturer": {"@id": f"{SITE}/#organization"},
        "category": "Health & Beauty > Aromatherapy > Essential Oil Blends",
        "size": blend["k"],
        "offers": {
            "@type": "Offer",
            "url": f"{SITE}/contact.html?topic=order",
            "price": price,
            "priceCurrency": "EUR",
            "availability": "https://schema.org/PreOrder",
            "itemCondition": "https://schema.org/NewCondition",
            "priceValidUntil": "2027-08-31",
            "seller": {"@id": f"{SITE}/#organization"},
        },
    }

    review = blend.get("review")
    if isinstance(review, dict) and review.get("text"):
        product["review"] = {
            "@type": "Review",
            "reviewBody": review["text"],
            "author": {"@type": "Person", "name": review.get("author", "Customer")},
            "reviewRating": {
                "@type": "Rating",
                "ratingValue": "5",
                "bestRating": "5",
                "worstRating": "1",
            },
        }

    crumbs = {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": f"{SITE}/"},
            {"@type": "ListItem", "position": 2, "name": "Collections",
             "item": f"{SITE}/collections.html"},
            {"@type": "ListItem", "position": 3, "name": source["collection"],
             "item": f"{SITE}/{source['collection_url']}"},
            {"@type": "ListItem", "position": 4, "name": blend["name"], "item": url},
        ],
    }

    graph = {"@context": "https://schema.org", "@graph": [product, crumbs]}
    return json.dumps(graph, ensure_ascii=False, separators=(", ", ": "))


LIST_START = "<!-- blend-pages start -->"
LIST_END = "<!-- blend-pages end -->"


def add_modal_link(source: dict) -> bool:
    """Give the pop-up a link to the blend's own page."""
    path = ROOT / source["file"]
    text = path.read_text(encoding="utf-8")
    linked = (
        "document.getElementById('pmBody').innerHTML = d.body + "
        "'<a class=\"pm-fullpage\" href=\"products/' + slug + '.html\">"
        "Read the full page for ' + d.name + ' \\u2192</a>';"
    )
    if linked in text:
        return False

    # Matches the untouched line and any earlier version of this patch, so the
    # link can be repointed without hand-editing the collection page.
    pattern = re.compile(r"document\.getElementById\('pmBody'\)\.innerHTML = d\.body[^\n]*?;")
    if not pattern.search(text):
        sys.exit(f"ERROR: could not find the modal body line in {source['file']}")
    path.write_text(pattern.sub(lambda _: linked, text, count=1), encoding="utf-8")
    return True


def add_link_list(source: dict, blends: list) -> None:
    """A plain, always-visible index of the blends, so crawlers can follow them."""
    path = ROOT / source["file"]
    text = path.read_text(encoding="utf-8")

    rows = "\n".join(
        f'        <li><a href="{f}">{esc(n)}</a></li>'
        for _, f, n, _ in blends
    )
    block = (
        f"{LIST_START}\n"
        '  <section class="wrap-text bp-index">\n'
        '    <span class="label">Every blend, on its own page</span>\n'
        f'    <h2 class="serif">All {len(blends)} formulas</h2>\n'
        '    <p>Each blend has a page of its own, with the full description, '
        "how to use it, what is in it and its cautions.</p>\n"
        "      <ul>\n"
        f"{rows}\n"
        "      </ul>\n"
        f"  </section>\n  {LIST_END}"
    )

    if LIST_START in text and LIST_END in text:
        text = re.sub(
            re.escape(LIST_START) + r".*?" + re.escape(LIST_END),
            lambda _: block,
            text,
            flags=re.S,
        )
    else:
        if "</main>" not in text:
            sys.exit(f"ERROR: no </main> in {source['file']}")
        text = text.replace("</main>", "  " + block + "\n\n</main>", 1)

    path.write_text(text, encoding="utf-8")


def update_sitemap(index: list) -> int:
    path = ROOT / "sitemap.xml"
    text = path.read_text(encoding="utf-8")

    START, END = "<!-- blend-pages start -->", "<!-- blend-pages end -->"
    entries = []
    for slug, filename, name, _ in index:
        entries.append(
            "  <url>\n"
            f"    <loc>{SITE}/{filename}</loc>\n"
            "    <lastmod>2026-08-25</lastmod>\n"
            "    <changefreq>monthly</changefreq>\n"
            "    <priority>0.8</priority>\n"
            "    <image:image>\n"
            f"      <image:loc>{SITE}/assets/img/products/{slug}.webp</image:loc>\n"
            f"      <image:title>{esc(name)}</image:title>\n"
            "    </image:image>\n"
            "  </url>"
        )
    block = START + "\n" + "\n".join(entries) + "\n  " + END

    if START in text and END in text:
        text = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, text, flags=re.S)
    else:
        text = text.replace("</urlset>", "  " + block + "\n\n</urlset>", 1)

    path.write_text(text, encoding="utf-8")
    return len(entries)


def main() -> None:
    written, index = [], []

    for source in SOURCES:
        data = load(source)
        slugs = list(data)
        for position, (slug, blend) in enumerate(data.items()):
            siblings = [slugs[(position + step) % len(slugs)] for step in range(1, 5)]
            more = "\n".join(
                '        <li><a href="{s}.html">'
                '<span class="frame"><img src="../assets/img/products/{s}.webp" alt="" '
                'loading="lazy" decoding="async" width="640" height="640" data-onerr="hide"></span>'
                '<span class="bp-more-name">{n}</span>'
                '<span class="bp-more-for">{f}</span></a></li>'.format(
                    s=other, n=esc(data[other]["name"]), f=esc(data[other]["forline"])
                )
                for other in siblings
            )
            filename = f"products/{slug}.html"
            url = f"{SITE}/{filename}"
            image = f"assets/img/products/{slug}.webp"
            image_abs = f"{SITE}/{image}"

            summary = plain(blend["body"])
            description = summary[:155].rsplit(" ", 1)[0] + "…" if len(summary) > 155 else summary

            page = PAGE.format(
                title=esc(f"{blend['name']} · {source['collection']} | Temple of Sun"),
                og_title=esc(f"{blend['name']} · Temple of Sun"),
                description=esc(description),
                url=url,
                image=image,
                image_abs=image_abs,
                name=esc(blend["name"]),
                crumb=esc(blend["crumb"]),
                forline=esc(blend["forline"]),
                price=esc(blend["price"]),
                size=esc(blend["k"]),
                collection=esc(source["collection"]),
                collection_url=source["collection_url"],
                body=blend["body"],
                more=more,
                schema=build_schema(slug, blend, source, url, image_abs),
            )

            (ROOT / "products").mkdir(exist_ok=True)
            (ROOT / filename).write_text(page, encoding="utf-8")
            written.append(filename)
            index.append((slug, filename, blend["name"], source["collection"]))

    for source in SOURCES:
        mine = [row for row in index if row[3] == source["collection"]]
        add_modal_link(source)
        add_link_list(source, mine)

    listed = update_sitemap(index)

    print(f"product pages: {len(written)} written")
    for source in SOURCES:
        count = sum(1 for _, _, _, c in index if c == source["collection"])
        print(f"  {source['collection']}: {count}")
    print(f"  linked from both collection pages and {listed} sitemap entries")


if __name__ == "__main__":
    main()
